---
- name: Install MySQL
  hosts: all
  become: true
  vars_files:
    - vault/secrets.yml
    - vault/win_connect.yml
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
