- hosts: localhost
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
    - github_token: "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"
  # vars_files:
  #   - vault/secrets.yml

  tasks:
    - name: Create a GitHub Repo
      github_repo:
        github_auth_key: "{{github_token}}"
        username: "BigDogDad87"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result
